/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      "background-background": "#fcfcfd",
      "background-background-grey": "#eff0f3",
      "background-background-highlight": "#dcd6ff",
      "background-background-inverse": "#1e1f24",
      "border-border": "#1e1f24",
      "border-border-inverse": "#6347ff",
      "border-border-on-color": "#fcfcfd",
      "button-primary-bg-active": "#1800a3",
      "button-primary-bg-default": "#6347ff",
      "button-primary-bg-disabled": "#e7e8ec",
      "button-primary-bg-focus": "#401fff",
      "button-primary-bg-hover": "#2500f5",
      "button-primary-border-focus": "#12007a",
      "button-secondary-bg-active": "#6347ff80",
      "button-secondary-bg-focus": "#a899ff80",
      "button-secondary-bg-hover": "#a899ff80",
      "button-secondary-border-active": "#401fff",
      "button-secondary-border-default": "#6347ff",
      "button-secondary-border-fokus": "#12007a",
      "button-secondary-border-hover": "#6347ff",
      "button-secondary-border-secondary-disabled": "#d8d9e0",
      "button-tertiary-bg-active": "#6347ff80",
      "button-tertiary-bg-disabled": "#e7e8ec",
      "button-tertiary-bg-focus": "#a899ff80",
      "button-tertiary-bg-hover": "#a899ff80",
      "button-tertiary-border-focus": "#12007a",
      "icon-icon": "#1e1f24",
      "icon-icon-disabled": "#cdced7",
      "icon-icon-inverse": "#1f00c0",
      "icon-icon-on-color": "#fcfcfd",
      "icon-icon-on-color-disabled": "#b9bbc6",
      "text-text": "#1e1f24",
      "text-text-disabled": "#cdced7",
      "text-text-inverse": "#6347ff",
      "text-text-on-color": "#fcfcfd",
      "text-text-on-color-disabled": "#b9bbc6",
    },
    extend: {},
  },
  plugins: [],
};
